import type {Metadata} from "next";
import {ReactNode} from "react";

export const metadata: Metadata = {
    title: "Auth layout",
    description: "Generated by create next app",
};

export default function AuthLayout(
    {
        children,
    }: Readonly<{
        children: ReactNode;
    }>) {
    return (
        <>
            <h2>Auth layout</h2>
            <section>
                {children}
            </section>
        </>
    )
        ;
}
