import type {Metadata} from "next";
import {ReactNode} from "react";
import {Card} from "@radix-ui/themes";

export const metadata: Metadata = {
    title: "Auth layout",
    description: "Generated by create next app",
};

export default function AuthLayout(
    {
        children,
    }: Readonly<{
        children: ReactNode;
    }>) {
    return (
        <Card size="4">
            {children}
        </Card>
    )
}
