import type {Metadata} from "next";
import {ReactNode} from "react";

import {Card, Flex} from "@radix-ui/themes";

export const metadata: Metadata = {
    title: "Auth layout",
    description: "Generated by create next app",
};

export default function AuthLayout(
    {
        children,
    }: Readonly<{
        children: ReactNode;
    }>) {
    return (
        <Flex align="center" justify="center" height="100vh">
            <Card size="4">
                {children}
            </Card>
        </Flex>
    )
}
