import {User} from "./model/user";

export const users: User[] = [
    {
        id: '1',
        fullName: 'John Doe',
        email: 'john@email.com',
        role: 'administrator',
    },
    {
        id: '2',
        fullName: 'Doe John',
        email: 'doe@email.com',
        role: 'moderator',
    },
    {
        id: '3',
        fullName: 'Alex Brown',
        email: 'xxal@email.com',
        role: 'author',
    },
    {
        id: '4',
        fullName: 'Emma Watson',
        email: 'emma@email.com',
        role: 'administrator',
    },
    {
        id: '5',
        fullName: 'Michael Scott',
        email: 'michael@email.com',
        role: 'moderator',
    },
    {
        id: '6',
        fullName: 'Pam Beesly',
        email: 'pam@email.com',
        role: 'author',
    },
    {
        id: '7',
        fullName: 'Jim Halpert',
        email: 'jim@email.com',
        role: 'administrator',
    },
    {
        id: '8',
        fullName: 'Dwight Schrute',
        email: 'dwight@email.com',
        role: 'moderator',
    },
    {
        id: '9',
        fullName: 'Angela Martin',
        email: 'angela@email.com',
        role: 'author',
    },
    {
        id: '10',
        fullName: 'Kevin Malone',
        email: 'kevin@email.com',
        role: 'administrator',
    },
    {
        id: '11',
        fullName: 'Andy Bernard',
        email: 'andy@email.com',
        role: 'moderator',
    },
    {
        id: '12',
        fullName: 'Stanley Hudson',
        email: 'stanley@email.com',
        role: 'author',
    },
    {
        id: '13',
        fullName: 'Phyllis Vance',
        email: 'phyllis@email.com',
        role: 'administrator',
    },
    {
        id: '14',
        fullName: 'Ryan Howard',
        email: 'ryan@email.com',
        role: 'moderator',
    },
    {
        id: '15',
        fullName: 'Kelly Kapoor',
        email: 'kelly@email.com',
        role: 'author',
    },
    {
        id: '16',
        fullName: 'Toby Flenderson',
        email: 'toby@email.com',
        role: 'administrator',
    },
    {
        id: '17',
        fullName: 'Creed Bratton',
        email: 'creed@email.com',
        role: 'moderator',
    },
    {
        id: '18',
        fullName: 'Darryl Philbin',
        email: 'darryl@email.com',
        role: 'author',
    },
    {
        id: '19',
        fullName: 'Erin Hannon',
        email: 'erin@email.com',
        role: 'administrator',
    },
    {
        id: '20',
        fullName: 'Gabe Lewis',
        email: 'gabe@email.com',
        role: 'moderator',
    },
    {
        id: '21',
        fullName: 'Holly Flax',
        email: 'holly@email.com',
        role: 'author',
    },
    {
        id: '22',
        fullName: 'Jan Levinson',
        email: 'jan@email.com',
        role: 'administrator',
    },
    {
        id: '23',
        fullName: 'David Wallace',
        email: 'david@email.com',
        role: 'moderator',
    },
    {
        id: '24',
        fullName: 'Charles Miner',
        email: 'charles@email.com',
        role: 'author',
    },
    {
        id: '25',
        fullName: 'Jo Bennett',
        email: 'jo@email.com',
        role: 'administrator',
    },
    {
        id: '26',
        fullName: 'Robert California',
        email: 'robert@email.com',
        role: 'moderator',
    },
    {
        id: '27',
        fullName: 'Nellie Bertram',
        email: 'nellie@email.com',
        role: 'author',
    },
    {
        id: '28',
        fullName: 'Clark Green',
        email: 'clark@email.com',
        role: 'administrator',
    },
    {
        id: '29',
        fullName: 'Pete Miller',
        email: 'pete@email.com',
        role: 'moderator',
    },
    {
        id: '30',
        fullName: 'Hank Doyle',
        email: 'hank@email.com',
        role: 'author',
    }
];