import {ReactNode} from "react";
import type {Metadata} from "next";
import {Theme} from "@radix-ui/themes";
import {Background} from "@/share/ui/background";

import "@radix-ui/themes/styles.css";
import './globals.css'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout(
    {children, modal}: Readonly<{ children: ReactNode; modal: ReactNode }>) {
    return (
        <html lang="ru">
        <body>

        <Theme accentColor="iris">
            <Background/>
            {children}
            {modal}
        </Theme>
        </body>
        </html>
    );
}
