import { type Article, ContentItem } from "./model/article";

export const articles: Article[] = [
    // 1. Русские
    {
        id: "1",
        nationId: "1",
        title: "Русские: История и Культура",
        content: [
            { type: 'heading', level: 1, text: "Русские" },
            { type: 'paragraph', text: "Русские — крупнейший славянский народ, проживающий преимущественно в России и странах СНГ." },
            { type: 'heading', level: 2, text: "История" },
            { type: 'paragraph', text: "История русского народа начинается с Киевской Руси, а затем продолжается через Московское княжество и Российскую империю." },
            { type: 'heading', level: 2, text: "Культура" },
            { type: 'paragraph', text: "Русская культура богата литературой, музыкой и искусством, включая таких гениев, как Пушкин и Чайковский." },
            { type: 'heading', level: 3, text: "Традиции" },
            { type: 'list', items: ["Масленица", "Рождество", "День Победы"] },
            { type: 'heading', level: 3, text: "Песни" },
            { type: 'list', items: ["Классическая музыка", "Балалайка", "Фольклорные песни"] },
            { type: 'image', src: "https://pozdravlyamba.ru/wp-content/uploads/2020/12/26-Let-Kakaia-Svadba-Pozdravleniia-Kartinki-300x169.jpg" },
            { type: 'link', text: "Узнать больше", href: "https://example.com/russians" },
        ],
        author: "Лаврентьев Д.А.",
    },
    // 2. Буряты
    {
        id: "2",
        nationId: "2",
        title: "Буряты: Культура и Традиции",
        content: [
            { type: 'heading', level: 1, text: "Буряты" },
            { type: 'paragraph', text: "Буряты — тюркский народ, проживающий в Сибири, особенно в Бурятии." },
            { type: 'heading', level: 2, text: "История" },
            { type: 'paragraph', text: "Буряты имеют древнюю историю, связанную с монгольскими и тюркскими кочевыми племенами." },
            { type: 'heading', level: 2, text: "Культура" },
            { type: 'paragraph', text: "Бурятская культура включает шаманизм, буддизм и традиционные танцы, такие как йохор." },
            { type: 'heading', level: 3, text: "Традиции" },
            { type: 'list', items: ["Сагаалган", "Йохор", "Шаманские обряды"] },
            { type: 'heading', level: 3, text: "Музыка" },
            { type: 'list', items: ["Хоомей", "Баян", "Фольклор"] },
            { type: 'image', src: "https://example.com/buryats-culture.jpg" },
            { type: 'link', text: "Подробнее о бурятах", href: "https://example.com/buryats" },
        ],
        author: "Петров А.В.",
    },
    // 3. Украинцы
    {
        id: "3",
        nationId: "3",
        title: "Украинцы: Наследие и Образ жизни",
        content: [
            { type: 'heading', level: 1, text: "Украинцы" },
            { type: 'paragraph', text: "Украинцы — славянский народ, проживающий преимущественно в Украине и её диаспоре." },
            { type: 'heading', level: 2, text: "История" },
            { type: 'paragraph', text: "История украинцев включает Киевскую Русь, казацкие времена и борьбу за независимость." },
            { type: 'heading', level: 2, text: "Культура" },
            { type: 'paragraph', text: "Украинская культура богата вышивкой, песнями и блюдами, такими как борщ." },
            { type: 'heading', level: 3, text: "Традиции" },
            { type: 'list', items: ["Ивана Купала", "Рождество", "Веснянки"] },
            { type: 'heading', level: 3, text: "Музыка" },
            { type: 'list', items: ["Бандура", "Народные песни", "Кобза"] },
            { type: 'image', src: "https://example.com/ukrainians-culture.jpg" },
            { type: 'link', text: "Узнать больше", href: "https://example.com/ukrainians" },
        ],
        author: "Сидорова Е.К.",
    },
    // 4. Татары
    {
        id: "4",
        nationId: "4",
        title: "Татары: История и Традиции",
        content: [
            { type: 'heading', level: 1, text: "Татары" },
            { type: 'paragraph', text: "Татары — тюркский народ, проживающий в Татарстане, Башкортостане и других регионах." },
            { type: 'heading', level: 2, text: "История" },
            { type: 'paragraph', text: "Татары имеют богатую историю, связанную с Золотой Ордой и Казанским ханством." },
            { type: 'heading', level: 2, text: "Культура" },
            { type: 'paragraph', text: "Татарская культура включает музыку, танцы и национальную кухню, такую как чак-чак." },
            { type: 'heading', level: 3, text: "Традиции" },
            { type: 'list', items: ["Сабантуй", "Ураза-байрам", "Курбан-байрам"] },
            { type: 'heading', level: 3, text: "Музыка" },
            { type: 'list', items: ["Куйбышева", "Фольклорные песни", "Кубыз"] },
            { type: 'image', src: "https://example.com/tatars-culture.jpg" },
            { type: 'link', text: "Подробнее", href: "https://example.com/tatars" },
        ],
        author: "Иванов М.П.",
    },
    // 5. Армяне
    {
        id: "5",
        nationId: "5",
        title: "Армяне: Наследие и Культура",
        content: [
            { type: 'heading', level: 1, text: "Армяне" },
            { type: 'paragraph', text: "Армяне — древний народ, проживающий в Армении и диаспоре по всему миру." },
            { type: 'heading', level: 2, text: "История" },
            { type: 'paragraph', text: "Армяне имеют историю, уходящую в 3-е тысячелетие до н.э., включая принятие христианства." },
            { type: 'heading', level: 2, text: "Культура" },
            { type: 'paragraph', text: "Армянская культура богата литературой, музыкой и ковроткачеством." },
            { type: 'heading', level: 3, text: "Традиции" },
            { type: 'list', items: ["Вардavar", "День независимости", "Свадьбы"] },
            { type: 'heading', level: 3, text: "Музыка" },
            { type: 'list', items: ["Дудук", "Классическая музыка", "Фольклор"] },
            { type: 'image', src: "https://example.com/armenians-culture.jpg" },
            { type: 'link', text: "Узнать больше", href: "https://example.com/armenians" },
        ],
        author: "Григорян А.С.",
    },
    // 6. Азербайджанцы
    {
        id: "6",
        nationId: "6",
        title: "Азербайджанцы: Культура и Образ жизни",
        content: [
            { type: 'heading', level: 1, text: "Азербайджанцы" },
            { type: 'paragraph', text: "Азербайджанцы — тюркский народ, проживающий в Азербайджане и прилегающих регионах." },
            { type: 'heading', level: 2, text: "История" },
            { type: 'paragraph', text: "История азербайджанцев связана с древними государствами Кавказа и тюркскими империями." },
            { type: 'heading', level: 2, text: "Культура" },
            { type: 'paragraph', text: "Азербайджанская культура известна музыкой мугами и коврами." },
            { type: 'heading', level: 3, text: "Традиции" },
            { type: 'list', items: ["Новруз", "Свадьбы", "Фестивали"] },
            { type: 'heading', level: 3, text: "Музыка" },
            { type: 'list', items: ["Мугам", "Тари", "Классическая музыка"] },
            { type: 'image', src: "https://example.com/azerbaijanis-culture.jpg" },
            { type: 'link', text: "Подробнее", href: "https://example.com/azerbaijanis" },
        ],
        author: "Алиев Р.М.",
    },
    // 7. Киргизы
    {
        id: "7",
        nationId: "7",
        title: "Киргизы: Традиции и История",
        content: [
            { type: 'heading', level: 1, text: "Киргизы" },
            { type: 'paragraph', text: "Киргизы — тюркский народ, проживающий в Киргизии и соседних странах." },
            { type: 'heading', level: 2, text: "История" },
            { type: 'paragraph', text: "Киргизы имеют кочевую историю, связанную с Великой степью." },
            { type: 'heading', level: 2, text: "Культура" },
            { type: 'paragraph', text: "Киргизская культура включает эпос 'Манас' и традиционные игры." },
            { type: 'heading', level: 3, text: "Традиции" },
            { type: 'list', items: ["Орок-Зоок", "Бешбармак", "Науруз"] },
            { type: 'heading', level: 3, text: "Музыка" },
            { type: 'list', items: ["Комуз", "Фольклор", "Современная музыка"] },
            { type: 'image', src: "https://example.com/kyrgyz-culture.jpg" },
            { type: 'link', text: "Узнать больше", href: "https://example.com/kyrgyz" },
        ],
        author: "Керимов К.Б.",
    },
    // 8. Белорусы
    {
        id: "8",
        nationId: "8",
        title: "Белорусы: Наследие и Культура",
        content: [
            { type: 'heading', level: 1, text: "Белорусы" },
            { type: 'paragraph', text: "Белорусы — славянский народ, проживающий в Белоруссии и диаспоре." },
            { type: 'heading', level: 2, text: "История" },
            { type: 'paragraph', text: "История белорусов связана с Великим княжеством Литовским и Речью Посполитой." },
            { type: 'heading', level: 2, text: "Культура" },
            { type: 'paragraph', text: "Белорусская культура включает вышивку, песни и национальные танцы." },
            { type: 'heading', level: 3, text: "Традиции" },
            { type: 'list', items: ["Коляды", "Радуница", "Купалье"] },
            { type: 'heading', level: 3, text: "Музыка" },
            { type: 'list', items: ["Скрипка", "Фольклор", "Современные группы"] },
            { type: 'image', src: "https://example.com/belarusians-culture.jpg" },
            { type: 'link', text: "Подробнее", href: "https://example.com/belarusians" },
        ],
        author: "Ковалёв С.В.",
    },
    // 9. Узбеки
    {
        id: "9",
        nationId: "9",
        title: "Узбеки: Культура и Традиции",
        content: [
            { type: 'heading', level: 1, text: "Узбеки" },
            { type: 'paragraph', text: "Узбеки — тюркский народ, проживающий в Узбекистане и соседних странах." },
            { type: 'heading', level: 2, text: "История" },
            { type: 'paragraph', text: "История узбеков включает Тимуридов и Великий шёлковый путь." },
            { type: 'heading', level: 2, text: "Культура" },
            { type: 'paragraph', text: "Узбекская культура богата керамикой, музыкой и национальными блюдами." },
            { type: 'heading', level: 3, text: "Традиции" },
            { type: 'list', items: ["Навруз", "Свадьбы", "Фестивали"] },
            { type: 'heading', level: 3, text: "Музыка" },
            { type: 'list', items: ["Дутар", "Фольклор", "Современная музыка"] },
            { type: 'image', src: "https://example.com/uzbeks-culture.jpg" },
            { type: 'link', text: "Узнать больше", href: "https://example.com/uzbeks" },
        ],
        author: "Ахмедов Р.Т.",
    },
    // 10. Эвенки
    {
        id: "10",
        nationId: "10",
        title: "Эвенки: Жизнь и Культура",
        content: [
            { type: 'heading', level: 1, text: "Эвенки" },
            { type: 'paragraph', text: "Эвенки — коренной народ Севера, проживающий в Сибири и Дальнем Востоке." },
            { type: 'heading', level: 2, text: "История" },
            { type: 'paragraph', text: "Эвенки ведут кочевой образ жизни, связанный с оленеводством." },
            { type: 'heading', level: 2, text: "Культура" },
            { type: 'paragraph', text: "Эвенкийская культура включает шаманизм, оленеводство и традиционные танцы." },
            { type: 'heading', level: 3, text: "Традиции" },
            { type: 'list', items: ["Оленеводство", "Шаманские ритуалы", "Летние фестивали"] },
            { type: 'heading', level: 3, text: "Музыка" },
            { type: 'list', items: ["Бубен", "Фольклор", "Песни"] },
            { type: 'image', src: "https://example.com/evenkis-culture.jpg" },
            { type: 'link', text: "Подробнее", href: "https://example.com/evenkis" },
        ],
        author: "Семёнов П.И.",
    },
];